name: "🚫 Add AI-Artist"
description: "Suggest an artist making AI music"
title: "[AI-Artist] …"
labels: ["ai-artist"]
body:
  - type: input
    id: artist_url
    attributes:
      label: "Spotify artist URL"
      description: "Full link to the artist (e.g. https://open.spotify.com/artist/2G3zpEex5zoQWMF7Dcgg6e)"
      placeholder: "https://open.spotify.com/artist/…"
    validations:
      required: true

  - type: input
    id: example_track_url
    attributes:
      label: "Example track URL"
      description: "Full link to a song that clearly shows this is an AI artist (e.g. https://open.spotify.com/track/48m5xhQozoQH7EPCJnHdpo)"
      placeholder: "https://open.spotify.com/track/…"
    validations:
      required: true
      
  - type: input
    id: artist_name
    attributes:
      label: "Artist Name"
      description: "Name on Spotify"
      placeholder: "e.g. SynthVerse"
    validations:
      required: true

  - type: checkboxes
    id: ai_indicators
    attributes:
      label: "Why could this artist be AI-generated?"
      description: "Select all that apply. Providing context helps speed up verification."
      options:
        - label: "All releases since 2024"
        - label: "High number of releases in a short time"
        - label: "AI-style cover art"
        - label: "Audio artifacts (robotic sound, high dynamics)"
    validations:
      required: false

  - type: textarea
    id: other_reason
    attributes:
      label: "Additional notes or evidence"
      description: "Any extra context, links, or observations"
      placeholder: |
        - AI bio or label
        - External sources
        - Other suspicious signs…
    validations:
      required: false
